on: push

jobs:
  setup-slurm:
    runs-on: ubuntu-latest
    services:
        mysql:
          image: mysql:8.0
          env:
            MYSQL_ROOT_PASSWORD: root
          ports:
            - "8888:3306"
          options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3
    steps:
      - name: Setup Slurm
        uses: multimeric/setup-slurm-action@v1.0.2
        with:
            memory: 3000

      - run: sinfo --Node
