on: push

jobs:
  setup-slurm:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup Slurm
        uses: multimeric/setup-slurm-action@v1
        with:
            nodes: |
                [
                    { name: localhost, State: UNKNOWN, Sockets: 1, CoresPerSocket: 2, RealMemory: 1000 },
                    { name: localhost, State: UNKNOWN, Sockets: 1, CoresPerSocket: 2, RealMemory: 1000 },
                ]
