on: push

jobs:
  setup-slurm:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Slurm
        uses: multimeric/setup-slurm-action@v1.0.0
        with:
            nodes: |
                [
                    { name: localhost, State: UNKNOWN, Sockets: 1, CoresPerSocket: 2, RealMemory: 1000 },
                    { name: localhost, State: UNKNOWN, Sockets: 1, CoresPerSocket: 2, RealMemory: 1000 },
                ]
