on: push

jobs:
  setup-slurm:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Slurm
        uses: multimeric/setup-slurm-action@v1.0.2
        with:
            memory: 3000

      - run: sinfo --Node
